version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    ports:
      - "${DB_PORT}:5432"
