"""users

Revision ID: 016a3f3972e8
Revises: 
Create Date: 2023-07-28 15:35:13.271787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016a3f3972e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('steamid', sa.String(length=64), nullable=False),
    sa.Column('personaname', sa.Text(), nullable=True),
    sa.Column('profileurl', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('avatarmedium', sa.Text(), nullable=True),
    sa.Column('avatarfull', sa.Text(), nullable=True),
    sa.Column('personastate', sa.Integer(), nullable=True),
    sa.Column('communityvisibilitystate', sa.Integer(), nullable=True),
    sa.Column('profilestate', sa.Integer(), nullable=True),
    sa.Column('lastlogoff', sa.Integer(), nullable=True),
    sa.Column('commentpermission', sa.Boolean(), nullable=True),
    sa.Column('realname', sa.Text(), nullable=True),
    sa.Column('primaryclanid', sa.Text(), nullable=True),
    sa.Column('timecreated', sa.Integer(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('gameserverip', sa.Integer(), nullable=True),
    sa.Column('gameextrainfo', sa.Text(), nullable=True),
    sa.Column('cityid', sa.Integer(), nullable=True),
    sa.Column('loccountrycode', sa.Text(), nullable=True),
    sa.Column('locstatecode', sa.Text(), nullable=True),
    sa.Column('loccityid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('steamid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
