"""5

Revision ID: 0dc64f09eb3b
Revises: 4b27b13d9875
Create Date: 2023-08-04 14:40:07.966406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dc64f09eb3b'
down_revision = '4b27b13d9875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assetstacks', 'virtual')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('virtual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
