"""users-columns-added

Revision ID: 1359d38bd4df
Revises: 016a3f3972e8
Create Date: 2023-07-28 15:54:06.505308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1359d38bd4df'
down_revision = '016a3f3972e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personastateflags', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatarhash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatarhash')
    op.drop_column('users', 'personastateflags')
    # ### end Alembic commands ###
