"""init

Revision ID: 2312d9eec53a
Revises: 
Create Date: 2023-07-31 17:01:17.520893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2312d9eec53a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('classid', sa.String(length=64), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=True),
    sa.Column('market_hash_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('background_color', sa.String(length=64), nullable=True),
    sa.Column('name_color', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('classid')
    )
    op.create_table('users',
    sa.Column('steamid', sa.String(length=64), nullable=False),
    sa.Column('personaname', sa.Text(), nullable=True),
    sa.Column('personastateflags', sa.Integer(), nullable=True),
    sa.Column('profileurl', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('avatarhash', sa.Text(), nullable=True),
    sa.Column('avatarmedium', sa.Text(), nullable=True),
    sa.Column('avatarfull', sa.Text(), nullable=True),
    sa.Column('personastate', sa.Integer(), nullable=True),
    sa.Column('communityvisibilitystate', sa.Integer(), nullable=True),
    sa.Column('profilestate', sa.Integer(), nullable=True),
    sa.Column('lastlogoff', sa.Integer(), nullable=True),
    sa.Column('commentpermission', sa.Boolean(), nullable=True),
    sa.Column('realname', sa.Text(), nullable=True),
    sa.Column('primaryclanid', sa.Text(), nullable=True),
    sa.Column('timecreated', sa.Integer(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('gameserverip', sa.Integer(), nullable=True),
    sa.Column('gameextrainfo', sa.Text(), nullable=True),
    sa.Column('cityid', sa.Integer(), nullable=True),
    sa.Column('loccountrycode', sa.Text(), nullable=True),
    sa.Column('locstatecode', sa.Text(), nullable=True),
    sa.Column('loccityid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classid', sa.String(length=64), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['items.classid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
