"""7

Revision ID: 2821eb34aaf2
Revises: 2ccfc2c16066
Create Date: 2023-08-04 16:10:12.390048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2821eb34aaf2'
down_revision = '2ccfc2c16066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('average_buyin', sa.Float(), nullable=True))
    op.drop_column('assetstacks', 'buyin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('buyin', mysql.FLOAT(), nullable=True))
    op.drop_column('assetstacks', 'average_buyin')
    # ### end Alembic commands ###
