"""10

Revision ID: 286ac1eddaf2
Revises: b042cfe5e8ba
Create Date: 2023-08-06 15:58:19.556085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '286ac1eddaf2'
down_revision = 'b042cfe5e8ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('virtual', sa.Boolean(), nullable=True))
    op.add_column('assetstacks', sa.Column('virtual_size', sa.Integer(), nullable=True))
    op.drop_column('assetstacks', 'virtuell_size')
    op.drop_column('assetstacks', 'virtuell')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('virtuell', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('assetstacks', sa.Column('virtuell_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('assetstacks', 'virtual_size')
    op.drop_column('assetstacks', 'virtual')
    # ### end Alembic commands ###
