"""6

Revision ID: 2ccfc2c16066
Revises: 0dc64f09eb3b
Create Date: 2023-08-04 15:12:07.303488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccfc2c16066'
down_revision = '0dc64f09eb3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
