"""11

Revision ID: 3ce09a6ea9fa
Revises: 286ac1eddaf2
Create Date: 2023-08-06 17:01:52.093425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce09a6ea9fa'
down_revision = '286ac1eddaf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_stackid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'assetstacks', ['asset_stackid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'asset_stackid')
    # ### end Alembic commands ###
