"""4

Revision ID: 4b27b13d9875
Revises: d1339914fe40
Create Date: 2023-08-04 14:37:39.380546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b27b13d9875'
down_revision = 'd1339914fe40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyinstacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assetid', sa.String(length=64), nullable=True),
    sa.Column('asset_stackid', sa.Integer(), nullable=True),
    sa.Column('buyin', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('virtual', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['asset_stackid'], ['assetstacks.id'], ),
    sa.ForeignKeyConstraint(['assetid'], ['assets.assetid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyinstacks')
    # ### end Alembic commands ###
