"""2

Revision ID: 55e2d375316f
Revises: 63934c1a37ca
Create Date: 2023-08-07 12:28:07.276246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e2d375316f'
down_revision = '63934c1a37ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
