"""users-columns-changed

Revision ID: 5b5c99ac3053
Revises: 1359d38bd4df
Create Date: 2023-07-28 15:58:21.837815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5c99ac3053'
down_revision = '1359d38bd4df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
