"""join fix

Revision ID: 651d0bc6f394
Revises: 2312d9eec53a
Create Date: 2023-07-31 17:11:51.353643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651d0bc6f394'
down_revision = '2312d9eec53a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
