"""12

Revision ID: 6bf908900c47
Revises: 3ce09a6ea9fa
Create Date: 2023-08-06 18:47:49.760513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf908900c47'
down_revision = '3ce09a6ea9fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
