"""2

Revision ID: 7da7f94fcf62
Revises: f2543a369cfa
Create Date: 2023-08-02 12:31:31.028265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da7f94fcf62'
down_revision = 'f2543a369cfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
