"""8

Revision ID: 830bb560dcf2
Revises: 2821eb34aaf2
Create Date: 2023-08-06 12:13:45.640939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830bb560dcf2'
down_revision = '2821eb34aaf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_nameid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_nameid')
    # ### end Alembic commands ###
