"""9

Revision ID: b042cfe5e8ba
Revises: 830bb560dcf2
Create Date: 2023-08-06 15:57:14.412072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b042cfe5e8ba'
down_revision = '830bb560dcf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyinstacks')
    op.add_column('assetstacks', sa.Column('buyin', sa.Float(), nullable=True))
    op.add_column('assetstacks', sa.Column('virtuell', sa.Boolean(), nullable=True))
    op.add_column('assetstacks', sa.Column('virtuell_size', sa.Integer(), nullable=True))
    op.drop_column('assetstacks', 'size')
    op.drop_column('assetstacks', 'average_buyin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assetstacks', sa.Column('average_buyin', mysql.FLOAT(), nullable=True))
    op.add_column('assetstacks', sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('assetstacks', 'virtuell_size')
    op.drop_column('assetstacks', 'virtuell')
    op.drop_column('assetstacks', 'buyin')
    op.create_table('buyinstacks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('assetid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('asset_stackid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('buyin', mysql.FLOAT(), nullable=True),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('virtual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_stackid'], ['assetstacks.id'], name='buyinstacks_ibfk_1'),
    sa.ForeignKeyConstraint(['assetid'], ['assets.assetid'], name='buyinstacks_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
