"""3

Revision ID: beb0f8027f4e
Revises: 55e2d375316f
Create Date: 2023-08-07 12:28:52.086703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb0f8027f4e'
down_revision = '55e2d375316f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricehistories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classid', sa.String(length=64), nullable=True),
    sa.Column('vendorid', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['items.classid'], ),
    sa.ForeignKeyConstraint(['vendorid'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classid', 'vendorid', 'time_stamp', name='unique_class_and_vendor_id_and_time_stamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricehistories')
    # ### end Alembic commands ###
