"""join fix2

Revision ID: d78e3c5008f8
Revises: 651d0bc6f394
Create Date: 2023-07-31 17:23:19.957234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78e3c5008f8'
down_revision = '651d0bc6f394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
