"""vendors and vendor_offers 3

Revision ID: e045623f0ed6
Revises: 
Create Date: 2023-08-02 12:27:20.810460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e045623f0ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('classid', sa.String(length=64), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=True),
    sa.Column('market_hash_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('background_color', sa.String(length=64), nullable=True),
    sa.Column('name_color', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('classid')
    )
    op.create_table('users',
    sa.Column('steamid', sa.String(length=64), nullable=False),
    sa.Column('personaname', sa.Text(), nullable=True),
    sa.Column('personastateflags', sa.Integer(), nullable=True),
    sa.Column('profileurl', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('avatarhash', sa.Text(), nullable=True),
    sa.Column('avatarmedium', sa.Text(), nullable=True),
    sa.Column('avatarfull', sa.Text(), nullable=True),
    sa.Column('personastate', sa.Integer(), nullable=True),
    sa.Column('communityvisibilitystate', sa.Integer(), nullable=True),
    sa.Column('profilestate', sa.Integer(), nullable=True),
    sa.Column('lastlogoff', sa.Integer(), nullable=True),
    sa.Column('commentpermission', sa.Boolean(), nullable=True),
    sa.Column('realname', sa.Text(), nullable=True),
    sa.Column('primaryclanid', sa.Text(), nullable=True),
    sa.Column('timecreated', sa.Integer(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('gameserverip', sa.Integer(), nullable=True),
    sa.Column('gameextrainfo', sa.Text(), nullable=True),
    sa.Column('cityid', sa.Integer(), nullable=True),
    sa.Column('loccountrycode', sa.Text(), nullable=True),
    sa.Column('locstatecode', sa.Text(), nullable=True),
    sa.Column('loccityid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('provision', sa.Float(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classid', sa.String(length=64), nullable=True),
    sa.Column('vendorid', sa.Integer(), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('lowest_price', sa.Integer(), nullable=True),
    sa.Column('median_price', sa.Integer(), nullable=True),
    sa.Column('sell_listings', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['items.classid'], ),
    sa.ForeignKeyConstraint(['vendorid'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_offers')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
