"""1

Revision ID: f2543a369cfa
Revises: e045623f0ed6
Create Date: 2023-08-02 12:30:08.996836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2543a369cfa'
down_revision = 'e045623f0ed6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
